### ISSUE TITLE
关于多说评论框

### ISSUE THREAD

**Issue by rorschach** [MrFuFuFu/mrfufufu.github.io#1]
您好，我发现您和我使用的博客模板是同一个，但是我一直不知道如何使用多说模板代码，请问具体该如何使用？

**Comment by MrFuFuFu** [comment]
你好，你可以在多说的，工具里找到你自己的模板代码，拷贝到对应的文件下面就行了，http://mrfu.duoshuo.com/admin/tools/

事实上 [Huxpro](https://github.com/Huxpro) 在他的实现里[huxpro.github.io](https://github.com/Huxpro/huxpro.github.io) 是可以直接通过 _config.xml 来配置的，我这里现在也是这么配置的，直接写上多说要的设置就行了

**Comment by rorschach** [comment]
搞定了，谢谢:)
